create sequence hibernate_sequence start 1 increment 1;

create table weather_list
(
    id int8 generated by default as identity,
    city_name varchar(255),
    date_of_request timestamp,
    feels_like_temperature float8,
    humidity float8,
    pressure float8,
    source varchar(255),
    temperature float8,
    wind_degree int4,
    wind_speed float8,
    primary key (id));

create table city
(
    id           int8 generated by default as identity,
    name         varchar(255) not null,
    country_code         varchar(255) not null,
    primary key (id)
);